### ISSUE TITLE
Provide a PTY-only class

### ISSUE THREAD

**Issue by m-dhooge** [joernheissler/trio-serial#2]
Hello,

When testing, I find it usually more convenient to emulate the serial line with `socat`…

Unfortunately, the linux SerialStream class tries to set the RTS serial-specific bit and that triggers an Exception.
Then, since SerialStream inherits from trio.Stream, I tried to stay at this higher level of abstraction. But only the trio-serial code knows that such a stream can be in a state that is neither EoF nor data-ready! So I was stuck again.

So I created the following class:
```
class PtyStream(ts.SerialStream):
    def _set_bit(self, bit: bytes, value: bool) -> None:
        pass

    def _get_bit(self, bit: int) -> bool:
        return False
```

I'm not sure what would be the best way to have something like this in the lib. Ideally, have a factory that analyses the provided path and choose which class to use…

HTH
M.

**Comment by m-dhooge** [comment]
A sample pytest using `socat` and the proposed class.
https://gist.github.com/m-dhooge/8fe0eae1bc401728a70b52282be2b714

**Comment by joernheissler** [comment]
Hello!

I don't think that auto detection is the best way to go. Your code passes names like `front.pty`. This is clearly unsuitable. It might be possible to read the symlink or to get the major/minor numbers of the device file. This will all fail in uncommon setups. Another option could be to use `os.ttyname` but that doesn't look very reliable either: on my system it does `readlink("/proc/self/fd/X")`.

Pyserial ignores the error in the constructor, but not on manual calls to `rts = X`: https://github.com/pyserial/pyserial/blob/master/serial/serialposix.py#L334-L342

I'm considering removing the handling of the modem bits from the constructor and aopen. The user would always have to call the function manually. Small benefit would be that it's then possible to not change the bit's state at all. The user would then either need to catch the errors or override the functions like you did. That's not very convenient, but it's a bit less magic.

Would https://github.com/joernheissler/trio-serial/pull/3 work for your?

**Comment by m-dhooge** [comment]
Hi,
You're right that auto-detection is error-prone, but I didn't want to remove the RTS part of your code… But if you believe you can drop it, I'm ok with that, of course!

> Would #3 work for your?

Just by removing line 84 of posix.py, my code is running again with the SerialStream class. So, yes, #3 works for me.

Thanks!
