### ISSUE TITLE
shutdown issue (RuntimeError: must be called from async context)

### ISSUE THREAD

**Issue by jsiverskog** [joernheissler/trio-serial#4]
hi,
if i ctrl-c my program when trio-serial is enabled i get:
```
Exception ignored in: <function AbstractSerialStream.__del__ at 0x7f1c01048280>
Traceback (most recent call last):
  File "env/lib/python3.9/site-packages/trio_serial/abstract.py", line 146, in __del__
    self.close()
  File "env/lib/python3.9/site-packages/trio_serial/posix.py", line 98, in close
    trio.lowlevel.notify_closing(fd)
  File "env/factory-tencho-env/lib/python3.9/site-packages/trio/_core/_generated_io_epoll.py", line 32, in notify_closing
    raise RuntimeError("must be called from async context")
RuntimeError: must be called from async context
```
when reading up a bit on this it seems like you're not supposed to do such calls from `__del__` (https://github.com/python-trio/trio-asyncio/issues/44), but i'm not sure what the correct solution would look like.

i instantiate my port with:
```
        self._serial = SerialStream(self._port, exclusive=True,
                                    baudrate=baudrate, rtscts=rtscts)
        await self._serial.aopen()
```
and doesn't really do much more with it (yet).

any suggestion?

**Comment by joernheissler** [comment]
Hello, thanks for the report.

Minimal code:
```python3
#!/usr/bin/env python3

from trio import run
from trio_serial import SerialStream

serial = SerialStream("/dev/ttyS0")
run(serial.aopen)
```

https://github.com/python-trio/trio/blob/master/trio/_unix_pipes.py#L52-L74 is how trio solved this issue.

Does #5 work for you?

**Comment by jsiverskog** [comment]
what's the easiest way to run this project in "development/editable" mode? with `setup.py` you can always do `python setup.py develop` but google hasn't been helpful providing a solution for `pyproject.toml`.

**Comment by jsiverskog** [comment]
or, how can i just build the package to try it out?

**Comment by joernheissler** [comment]
`/path/to/venv/bin/pip install -U .`

Or you can install poetry and then run `poetry build -f wheel` and install the `.whl` with pip.

**Comment by jsiverskog** [comment]
simple :)

thanks.

i can confirm #5 fixes the issue!

super!
