### ISSUE TITLE
support readline()

### ISSUE THREAD

**Issue by craftyguy** [joernheissler/trio-serial#8]
pyserial has a method `readline` [1] to read a full line to a newline, or until a given timeout (set when instantiating the pyserial object). I think it would be useful to have in this library, though I'm not sure how difficult it would be to implement.

1. https://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.Serial.readline

**Comment by craftyguy** [comment]
after looking into it a little, this may not be straight forward.. pyserial uses an object derived from `IOBase` (so, it uses the `readline` stuff in the python stdlib for `IOBase`), and you're using a Trio `Stream` object here, which seems to be entirely different (and provides no `readline`).

**Comment by craftyguy** [comment]
I tried out this readline implementation, and it works well in trio-serial: https://github.com/pyserial/pyserial/issues/216#issuecomment-369414522

**Comment by joernheissler** [comment]
Timeouts should be handled by the caller in any case.
And I think high-level concepts like buffered streams should be handled elsewhere too.
There is for example https://github.com/oremanj/tricycle/blob/master/tricycle/_streams.py#L252

This works for me:
```python
from trio import run
from trio_serial import SerialStream
from tricycle import TextReceiveStream

async def main():
    async with SerialStream("/dev/ttyFTDI2") as ser, TextReceiveStream(ser, newline="\r") as lines:
       async for line in lines:
           print(f"Line: '{line.strip()}'")
           if "stop" in line:
               break

run(main)
```

**Comment by joernheissler** [comment]
There's related discussion on https://github.com/python-trio/trio/issues/796

**Comment by craftyguy** [comment]
Ah, thanks for the pointers to the existing issue on trio.

I filed this here because the description of this project in the readme is that it's an "adaptation of pyserial", and a readline method is implemented in pyserial, so I had expected something similar to be here. So that's just a misunderstanding on my part :)
